### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by luebken** [meanjs/mean#1674]
I've just did a `npm install`on a fresh copy of master and got the following.

```
...
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none was installed.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mdl/workspace/redhat/examples/meanjs-app/npm-debug.log
```

```
$ node --version
v7.2.0
```

**Comment by luebken** [comment]
I've fixed this by following the instructions from https://www.npmjs.com/package/eslint-config-airbnb

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```

But to be honest I don't know what happened there. Is that something that can be 
a) automated?
or
b) documented?

**Comment by lirantal** [comment]
@luebken can you explain more about your fix, I don't follow why/where we would need to do that.
You're welcome to propose a PR too.

**Comment by Jageen** [comment]
So @luebken not decided to share solution ?, I am still having issue @lirantal do you have any information regarding this.

**Comment by luebken** [comment]
@lirantal I'm sorry I can't explain the fix. I was just searching for the upmost warning and that link that I posted seemed to have done the trick. My assumption was that it had todo with some peerDependencies. But that is again a wild guess.
