### ISSUE TITLE
Production CSS/JS minification does not glob all source files

### ISSUE THREAD

**Issue by NeverOddOrEven** [meanjs/mean#183]
If you add a module with yeoman and then set NODE_ENV to production. If you run grunt build, then grunt, the app does not work. The new module JS is not included in the application.min.js nor are any new CSS styles added to application.min.css. 

I am looking at it now, but don't know yet how I will proceed to fix it. A temporary workaround is to not use minified JS. Remove config.assets.js and config.assets.css from production.js, and copy in the ones from all.js.

**Comment by ilanbiala** [comment]
@NeverOddOrEven is this still an issue? I don't think I noticed it, but then again I'm running a version a little before 9/14/14.

**Comment by NeverOddOrEven** [comment]
0.3.x branch is low on my priority list right now. I'll need to revisit this later. To test it, you need to add a new CRUD module and then run the production build/deploy.

If the module works, then this can be closed. If not, then it is still an issue.

**Comment by Edo78** [comment]
I can confirm th bug in the 0.3.x branch.
I just generate a new app `yo meanjs` then I tested that `NODE_ENV=development grunt` works as intended but `NODE_ENV=production grunt`  give no errors but the app isn't showing anymore

`NODE_EVN=production grunt build` generate public/dist/application.js and public/dist/application.min.js both empty

**Comment by jtweeks** [comment]
Same here can't build in production
Running "cssmin:combine" (cssmin) task
>> Destination not written because minified CSS was empty.

**Comment by codydaig** [comment]
Sounds like these issues have been resolved in the 0.4.0 branch.
Can anyone confirm?

**Comment by lirantal** [comment]
@NeverOddOrEven @Edo78 any chance you guys can confirm if these issues are still relevant in the current master branch? thanks

**Comment by codydaig** [comment]
@lirantal From looking at my the current code and the output of the build process, it seems like this has been resolved. Shall we close this issue?

@NeverOddOrEven @Edo78 If your still having issues with this, feel free to open a new issue!

**Comment by lirantal** [comment]
Yep, it's quite old and no one replies back so let's close otherwise people can re-comment still.
