### ISSUE TITLE
0.4.0 'gulp test' hangs because mongoose connections are staying open

### ISSUE THREAD

**Issue by reblace** [meanjs/mean#450]
The mongoose connection opened as part of the 'test' task in the gulp build is never closed. This causes gulp to hang at the completion of the tests.

**Comment by ilanbiala** [comment]
Does the referenced commit and changes made in `gulpfile.js` and `config/lib/mongoose.js` fix the issue?.

**Comment by reblace** [comment]
You commit only references the gulpfile. I think you want to pass a callback into the disconnect method on the mongoose connection so you can call the gulp done method when the disconnect is complete. Eg:

mongoose.disconnect(function(err) {
	done(err);
});

Then, you can have the config/lib/mongoose.js file do something like this:

module.exports.disconnect = function(cb) {
	db.disconnect(function(err) {
		cb(err);
	});
};

**Comment by ilanbiala** [comment]
Fixed in the latest commit.

**Comment by reblace** [comment]
You can't do this:
> mongoose.connect(done);
because gulp interprets any parameter to the callback (done) as an error. So, in this case, the build immedaitely fails on the connect when the connect function returns a refernece to the database.

So, you need to do this instead on the openMongoose task:

mongoose.connect(function(db) {
	done();
});

**Comment by ilanbiala** [comment]
[The build](https://travis-ci.org/meanjs/mean/builds/53291197) passes.

**Comment by reblace** [comment]
> meanjs@0.4.0 test /home/travis/build/meanjs/mean
> grunt test

It isn't running the gulp build.

**Comment by ilanbiala** [comment]
Out of curiosity, what error does Gulp throw because of that?

**Comment by reblace** [comment]
Gulp fails because the task is reporting an error:

[22:53:28] 'openMongoose' errored after 247 ms
[22:53:28] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:161:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:187:15)
    at Gulp.emit (events.js:129:20)

You can check out the branch and do a "gulp test" to reproduce.

**Comment by ilanbiala** [comment]
Fixed in the latest commit.

**Comment by reblace** [comment]
Fixed.

**Comment by reblace** [comment]
Just discovered that this issue isn't entirely fixed. The remaining issue is that when the tests fail, the 'closeMongoose' task isn't called, so the build still hangs.

One solution is to suppress errors on both the mocha and karma build tasks... eg:

// Mocha tests task
gulp.task('mocha', function () {
	return gulp.src(testAssets.tests.server)
		.pipe(plugins.mocha({
			reporter: 'spec'
		}))
		.on('error', function (err) {
			// Make sure failed tests don't cause gulp to exit, otherwise Mongoose won't cleanup
			this.emit('end');
		});
});

// Karma test runner task
gulp.task('karma', function (done) {
	return gulp.src([])
		.pipe(plugins.karma({
			configFile: 'karma.conf.js',
			action: 'run',
			singleRun: true
		}))
		.on('error', function (err) {
			// Make sure failed tests cause gulp to exit non-zero
			this.emit('end');
		});
});

If you do that, then the gulp tasks will run to completion and the 'closeMongoose' task will run.

But, the issue with this approach is I don't think a CI server will know that the tests failed when they do.

**Comment by ilanbiala** [comment]
I think a big issue is using runSequence because that doesn't seem to handle error propagation properly. Can you please format your code with syntax highlighting and proper indentation using markdown?

**Comment by reblace** [comment]
Submitted a pull request for fixing this: https://github.com/meanjs/mean/pull/453

I changed the gulpfile so the mocha task calls mongoose.disconnect regardless of if the mocha tests pass or fail and passes the error back to the done callback if it exists.

**Comment by ilanbiala** [comment]
Just merged #453 in, so this should be fixed.
